import { Users } from './data-model'

export const MYDATA:Users[] = [
    {
        id:1,
        name:"sundaravel",
        username:"sundar123",
        state:"TN",
        city:"Salem",
        pincode:123456
    },
    {
        id:2,
        name:"Mark",
        username:"mdo",
        state:"USA",
        city:"NY",
        pincode:741852
    },
    {
        id:3,
        name:"Jacob",
        username:"Thornton",
        state:"TN",
        city:"Salem",
        pincode:852963
    },
    {
        id:4,
        name:"Larry",
        username:"Larry",
        state:"TN",
        city:"Salem",
        pincode:987654
    },
    {
        id:5,
        name:"Thornton",
        username:"Thornton",
        state:"TN",
        city:"Salem",
        pincode:321654
    },
    {
        id:6,
        name:"Otto",
        username:"Otto",
        state:"TN",
        city:"Salem",
        pincode:123456
    }
];